// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// addHD
Rcpp::NumericVector addHD(Rcpp::NumericVector x, Rcpp::NumericVector y, bool verbose = false);
RcppExport SEXP RcppHyperDual_addHD(SEXP xSEXP, SEXP ySEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP );
        Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP );
        Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP );
        Rcpp::NumericVector __result = addHD(x, y, verbose);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
