# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' This function adds two hyper-dual numbers
#' 
#' @title Add two hyper-dual numbers
#' @param x A vector of length four containg a hyper-dual number
#' @param y A vector of length four containg a hyper-dual number
#' @param verbose A boolean variable with default \sQuote{false} 
#' indicating if verbose operation is desired.
#' @return A vector of length four containing the resulting
#' hyper-dual number.
#' @author Dirk Eddelbuettel
#' @examples
#'
#' addHL( c(1,0,0,1), c(2,1,0,-1) )
addHL <- function(x, y, verbose = FALSE) {
    .Call('RcppHyperDual_addHL', PACKAGE = 'RcppHyperDual', x, y, verbose)
}

